name: On Merge

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/wf-test.yml

  release:
    uses: ./.github/workflows/wf-release.yml
    with:
      release-pypi: false
