name: On Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/wf-test.yml

  release:
    uses: ./.github/workflows/wf-release.yml
    needs: [test]
    with:
      release-pypi: true
    secrets:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
