name: Test

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install 'poetry~=1.4.0'
          # workaround faulty wheels in the wild
          # https://github.com/python-poetry/poetry/issues/7686
          poetry config installer.modern-installation false
          poetry install

      - name: Test
        run: |
          poetry run pytest
